# Generated by Django 4.2 on 2023-04-29 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0002_rename_name_student_created_by_remove_student_marks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='content',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='student',
            name='title',
        ),
        migrations.AddField(
            model_name='student',
            name='marks',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='roll',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
